freshers<-scan("talman/trial_factors.csv", list(id=0,
                                         college="BITB",
                                         gender="m",
                                         branch="EEE",
                                         recruitment="OnCampus",
                                         native="Bangalore",
                                         father="teacher",
                                         mother="teacher",
                                         siblings=0,
                                         sisters=0,
                                         brothers=0,
                                         elderBrothers=0,
                                         youngerBrothers=0,
                                         elderSisters=0,
                                         youngerSisters=0,
                                         scoreX=0,
                                         scoreXII=0,
                                         reference="no",
                                         offers="NA",
                                         idleTime=0,
                                         trainings="no",
                                         associated="no",
                                         engagement=1), skip=1, sep=",")
  
